name: Print the date on windows

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:

  windows:
    name: Print the date on windows
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "powershell date $(powershell get-date -format "yyyyMMdd")"
          echo "DATE=$(powershell get-date -format "yyyyMMdd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "set date ${DATE}"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/cve-bin-tool
          key: ${{ runner.os }}-cve-bin-tool-${{ steps.get-date.outputs.DATE }}
