name: Print the date on windows

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:

  windows:
    name: Print the date on windows
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(powershell get-date -format "yyyyMMdd")" >> $GITHUB_OUTPUT
