name: Test environment

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print the thing
        env:
          TEST_ME: ${{ secrets.TEST_ME }}
        run: echo $TEST_ME
